### PR TITLE
Fix issue with context being cancelled prematurely

### LINKED ISSUE #69: Bug: polling health checker will always fail
We run into some trouble with client conn control, and trying to use the health check. however, the default health checker will always fail with its context deadline exceeded. I think its because the line 332 in `httplb/balancer.go`,  should use withtimeout instead of withcancel. 

```go
connection := conns[i]
connCtx, connCancel := context.WithCancel(b.ctx)
healthChecker := b.healthChecker.New(connCtx, connection, b)
go func() {
	defer connCancel()
	if err := connection.Prewarm(connCtx); err == nil {
		b.warmedUp(connection)
	}
}()
``` 

here is my test code 

```go
// server.go
package main

import (
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/healthcheck"
	"github.com/gofiber/fiber/v2/middleware/recover"
)

func main() {
	app := fiber.New()

	app.Use(recover.New())
	app.Use(healthcheck.New(
		healthcheck.Config{
			LivenessEndpoint: "/healthz",
			LivenessProbe: func(c *fiber.Ctx) bool {
				c.Send([]byte("OK"))
				return true
			}},
	))
	app.Get("/foo", func(c *fiber.Ctx) error {
		return c.Send([]byte("bar"))
	})
	app.Get("/", func(c *fiber.Ctx) error {
		return c.Send([]byte("bar"))
	})
	if err := app.Listen(":3000"); err != nil {
		panic(err)
	}
}

// client.go
package main

import (
	"fmt"
	"net/http"
	"net/url"
	"time"

	"github.com/bufbuild/httplb"
	"github.com/bufbuild/httplb/health"
)

func main() {

	url := url.URL{
		Scheme: "http",
		Host:   "localhost:3000",
		Path:   "foo",
	}

	client := httplb.NewClient(
		httplb.WithHealthChecks(
			health.NewPollingChecker(
				health.PollingCheckerConfig{
					Timeout:         100 * time.Second,
					PollingInterval: 100 * time.Second,
				},
				health.NewSimpleProber("/healthz"),
			),
		),
	)

	for range 5 {
		req, err := http.NewRequest(http.MethodGet, url.String(), http.NoBody)
		if err != nil {
			fmt.Println(err)
			continue
		}

		resp, err := client.Do(req)
		if err != nil {
			fmt.Println(err)
			continue
		}
		fmt.Println(resp.Status)
		time.Sleep(1 * time.Second)
	}
}
```

the error log 

```
200 OK
Get "http://localhost:3000/foo": unavailable: no healthy connections
Get "http://localhost:3000/foo": unavailable: no healthy connections
Get "http://localhost:3000/foo": unavailable: no healthy connections
Get "http://localhost:3000/foo": unavailable: no healthy connections
```

### PR DESCRIPTION
**Pull request by jhump**
There was a bug where we would cancel the health-checker's context after warming up the connection, which means that health checkers that rely on the context would start permanently failing after the first check.

To reproduce, I updated the `FakeHealthChecker` used in tests to be context-sensitive: it uses `context.AfterFunc` to permanently mark a connection as unhealthy if/when the context is cancelled.

One of my local test runs then hung, revealing a potential deadlock bug. The issue was that the balancer would acquire a lock and then call `check.Close()`. For the `FakeHealthChecker`, closing then acquires the health checker's lock. But over in the `FakeHealthChecker.UpdateHealthState`, we acquire locks in the reverse order: acquiring the health checker's lock and then calling `tracker.UpdateHealthState` (which ends up calling into the balancer and acquiring the balancer's lock). Having the lock acquisition order differ exposes a potential deadlock.

I fixed the deadlock by making it so that we don't ever try to acquire both locks at the same time, much less acquire them in different orders.
1. In the balancer, we no longer call `check.Close()` while holding a lock.
2. In `FakeHealthChecker`, we no longer call into the tracker while holding a lock.

Resolves #69.

### CODE REVIEW

File: balancer.go [hunk 1]
```diff
@@ -301,6 +301,12 @@ func (b *balancer) updateConns(newAddrs []resolver.Address, removeConns []conn.C
 			b.pool.RemoveConn(c)
 		}
 	}()
+	var checkClosers []io.Closer
+	defer func() {
+		for _, c := range checkClosers {
+			_ = c.Close()
+		}
+	}()
```
Comment (jhump) [inline balancer.go:309]: This was to prevent risk of deadlock. We don't want to be holding `b.mu` when calling `check.Close()`.

File: balancer.go [hunk 2]
```diff
@@ -331,12 +337,6 @@ func (b *balancer) initConnInfoLocked(conns []conn.Conn) {
 		connection := conns[i]
 		connCtx, connCancel := context.WithCancel(b.ctx)
 		healthChecker := b.healthChecker.New(connCtx, connection, b)
-		go func() {
-			defer connCancel()
```
Comment (jhump) [inline balancer.go:335]: This was the culprit. This cancellation is not needed. I also moved this block to the end since it doesn't really need to be kicked off here, and I thought it was slightly confusing to break up the rest of synchronous flow with this in the middle.

File: internal/balancertesting/balancertesting.go [hunk 3]
```diff
@@ -357,6 +357,14 @@ func (hc *FakeHealthChecker) New(_ context.Context, connection conn.Conn, tracke
...
 			close(ch)
 		}
+		context.AfterFunc(ctx, func() {
+			// Automatically force state to unhealthy after context is cancelled.
+			tracker := hc.updateHealthState(connection, health.StateUnhealthy, true)
+			if tracker == nil {
+				return
+			}
+			tracker.UpdateHealthState(connection, health.StateUnhealthy)
+		})
```
Comment (jhump) [inline internal/balancertesting/balancertesting.go:367]: This makes the test health checker context-aware, which reproduced the originally reported issue.

File: internal/balancertesting/balancertesting.go [hunk 4]
```diff
@@ -378,10 +386,24 @@ func (hc *FakeHealthChecker) New(_ context.Context, connection conn.Conn, tracke
 
 // UpdateHealthState allows the state of a connection to be changed.
 func (hc *FakeHealthChecker) UpdateHealthState(connection conn.Conn, state health.State) {
+	tracker := hc.updateHealthState(connection, state, false)
+	if tracker != nil {
+		tracker.UpdateHealthState(connection, state)
+	}
```
Comment (jhump) [inline internal/balancertesting/balancertesting.go:392]: We separate this step from the other updates (in helper below) so that we are _not_ holding `hc.mu` while calling into the tracker. This was the other side of the changes to eliminate possible deadlock.
